version: "2"
services:
  slapd:
    image: dcm4che/slapd-dcm4chee:2.4.44-10.5
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:3.2.1-1
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
    env_file: docker-compose.env
    environment:
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      KEYCLOAK_WAIT_FOR: ldap:389
    links:
      - slapd:ldap
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
