version: "2"
services:
  slapd:
    image: dcm4che/slapd-dcm4chee:5.6.0
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  keycloak:
    image: dcm4che/keycloak:2.1.0.Final
    ports:
      - "8080:8080"
      - "9990:9990"
    env_file: docker-compose.env
    environment:
      KEYCLOAK_WAIT_FOR: ldap:389
    links:
      - slapd:ldap
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/local/dcm4chee-arc/keycloak:/opt/keycloak/standalone
