version: "3"
services:
  keycloak:
    image: dockertest-ng.lan.j4care.com/keycloak:6.0.1-17.0
    ports:
      - "8880:8880"
      - "8843:8843"
      - "8990:8990"
      - "8993:8993"
      - "7600:7600"
    extra_hosts:
      - "test-ng:192.168.2.145"
    environment:
      KEYCLOAK_DB_HOST: gunter-nb
      JGROUPS_DISCOVERY_EXTERNAL_IP: test-ng
      JGROUPS_DISCOVERY_INITIAL_HOSTS: "gunter-nb[7600],test-ng[7600]"
      HTTP_PORT: 8880
      HTTPS_PORT: 8843
      MANAGEMENT_HTTP_PORT: 8990
      MANAGEMENT_HTTPS_PORT: 8993
      LDAP_URL: ldaps://gunter-nb:636
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/keycloak2:/opt/keycloak/standalone
